export const getNoteSuggestions = (name: string): string[] => [
  `Mind over matter, ${name} deserves this more than anyone! 🎁`,
  `I was going to buy ${name} a private island, but this seemed more practical... for now. 😉`,
  `${name}, manage this one first... more loading soon! 😂`,
  `Just a little something for ${name} to make today 100% better. 🚀`,
  `To ${name}, with love and zero self-control when it comes to gifting! ✨`,
  `Mind over matter, but ${name} is the only matter that minds! ❤️`,
  `${name}, I hope this gift is as awesome as our late-night chats! 🌙`,
  `Warning: This gift for ${name} may cause extreme happiness! ⚠️`,
  `To the person who has everything (except this): Enjoy, ${name}! 🎊`,
  `${name}, if you don't like this, I'm keeping it for myself! 😜`,
  `From me to ${name}: A small token of my massive appreciation. 💎`,
  `They say money can't buy happiness, but it bought this for ${name}! 💸`,
  `Mind over matter: I don't mind spending if it's for ${name}! 💳`,
  `${name}, prepare to be slightly more impressed than usual! 😎`,
  `To my favorite human ${name}: You're welcome! 😇`,
  `This gift is about 50% love and 50% 'I saw this and thought of ${name}'! 🧠`,
  `Keep calm and let ${name} open the best gift ever! 🧘‍♂️`,
  `${name}, you're the reason I'm broke this month, and I'm okay with it! 😂`,
  `May this gift bring a smile to ${name}'s face and a skip to their step! 🏃‍♀️`,
  `To ${name}: Because being awesome should be rewarded! 🏆`,
  `Mind over matter, ${name}, but this gift is definitely solid matter! 🧱`,
  `${name}, I hope this makes you feel like the VIP you are! 🌟`,
  `A little box of joy for a big-hearted person like ${name}! ❤️`,
  `${name}, consider this an official 'You're the best' certificate. 📜`,
  `To ${name}: May your day be as bright as your smile! ☀️`,
  `Mind over matter: I had a mind to get ${name} something great, and it mattered! 🧩`,
  `${name}, don't say I never did anything for you! 🤪`,
  `To the one and only ${name}: Stay legendary! 🦄`,
  `This gift for ${name} is guaranteed to be 100% better than a hug (barely)! 🤗`,
  `${name}, I hope this is exactly what you didn't know you wanted! 🎁`,
  `To ${name}: Just because you're you, and you're pretty great at it. 🎈`,
  `Mind over matter, ${name}. I spent a lot of mind-power picking this! ⚡`,
  `${name}, if this were a movie, this would be the best part! 🎬`,
  `To my partner in crime, ${name}: Enjoy the loot! 🏴‍☠️`,
  `${name}, I'm officially your favorite person now, right? 😇`,
  `A little something for ${name} because adulting is hard. 🍹`,
  `To ${name}: May this gift solve at least one of your minor problems! 🛠️`,
  `Mind over matter: I don't mind the bill, ${name}, you're worth it! 💰`,
  `${name}, you're officially the hardest person to shop for. Enjoy! 🛍️`,
  `To ${name}: A small gift for a person with a massive personality! 🎇`,
  `${name}, I hope this gift survives the unboxing video! 📹`,
  `From my heart to ${name}'s hands. Enjoy! ❤️`,
  `Mind over matter, ${name}. This gift is out of this world! 🛸`,
  `${name}, I hope this adds a little sparkle to your week! ✨`,
  `To the most deserving person I know: Enjoy, ${name}! 🥇`,
  `${name}, this gift is a bribe for you to keep being awesome. 🤝`,
  `To ${name}: Because everyone needs a little treat now and then! 🍫`,
  `Mind over matter, ${name}. I was minded to get you the best! 💎`,
  `${name}, I hope this gift makes you as happy as a kid in a candy store! 🍭`,
  `To ${name}: Just a reminder that you're totally crushing it! 💥`,
];
