// /data/vendors.ts

export interface Vendor {
  id: number;
  name: string;
  image: string;
  rating: number;
  category: string;
  badges: string[];
  giftIdeas: number;
}

export const vendors_food: Vendor[] = [
  // --- existing vendors (1–12) ---
  {
    id: 1,
    name: "Wakame Restaurant",
    image:
      "https://img.freepik.com/free-photo/cafe-terrace-with-turquoise-sofas-yellow-pillows_140725-2484.jpg?t=st=1757893526~exp=1757897126~hmac=3990e408ae0c85869c39f358b22a6ac2a715c59e6cc7806233ba55df1ce722a5&w=1480",
    rating: 9,
    category: "Food",
    badges: [
      "Pizza",
      "Rib-eye",
      "Steak",
      "Seafood",
      "Cocktails",
   
    ],
    giftIdeas: 9,
  },
  {
    id: 2,
    name: "SLOW",
    image:
      "https://img.freepik.com/free-photo/dinner-table-with-foods-soft-drinks-restaurant_114579-3319.jpg?t=st=1757893525~exp=1757897125~hmac=af5ba6df1c16f3a34fb93218f4328cd6b179333437405a2edc6a83cd50fff473&w=1480",
    rating: 9,
    category: "Food",
    badges: [
      "Delivery",
      "Takeout",
      "Asian Fusion",
      "Vegan Friendly",
 
    ],
    giftIdeas: 9,
  },
  {
    id: 3,
    name: "Shiro Lagos",
    image:
      "https://img.freepik.com/free-photo/group-diverse-friends-taking-selfie-with-mobile-phone-while-drinking-glass-beer-bar-friends-concept_58466-16340.jpg",
    rating: 9,
    category: "Food",
    badges: [
      "Sushi",
      "Cocktails",
      "Nightlife",
      "Live Music",
      "Seafood",
  
    ],
    giftIdeas: 9,
  },
  {
    id: 4,
    name: "Gras Restaurant",
    image:
      "https://img.freepik.com/free-photo/dinner-table-with-foods-soft-drinks-restaurant_114579-3319.jpg",
    rating: 9,
    category: "Food",
    badges: [
      "Italian",
      "Pasta",
      "Wood-fired Pizza",
      "Wine Cellar",
      "Outdoor Seating",

    ],
    giftIdeas: 9,
  },
  {
    id: 5,
    name: "Saturdays",
    image:
      "https://img.freepik.com/free-photo/cafe-terrace-with-turquoise-sofas-yellow-pillows_140725-2484.jpg?t=st=1757893526~exp=1757897126~hmac=3990e408ae0c85869c39f358b22a6ac2a715c59e6cc7806233ba55df1ce722a5&w=2000",
    rating: 9,
    category: "Food",
    badges: [
      "Brunch",
      "Coffee",
      "Smoothies",
      "Bakery",
      "Vegan Options",

    ],
    giftIdeas: 9,
  },
  {
    id: 6,
    name: "Cactus Restaurant",
    image: "https://images.pexels.com/photos/1307698/pexels-photo-1307698.jpeg",
    rating: 9,
    category: "Food",
    badges: [
      "Seafood",
      "Steaks",
      "Cocktails",
      "Riverside View",
      "Outdoor Dining",
      "Romantic",

    ],
    giftIdeas: 9,
  },
  {
    id: 7,
    name: "RSVP Restaurant",
    image:
      "https://images.pexels.com/photos/29544344/pexels-photo-29544344.jpeg",
    rating: 9,
    category: "Food",
    badges: [
      "Fusion Cuisine",
      "Cocktail Bar",
      "Poolside Dining",
      "Late Night",
      "DJ Nights",
      "Small Plates",

    ],
    giftIdeas: 9,
  },
  {
    id: 8,
    name: "Gabby",
    image:
      "https://images.pexels.com/photos/17370228/pexels-photo-17370228.jpeg",
    rating: 9,
    category: "Food",
    badges: [
      "Grill",
      "Burgers",
      "Craft Beer",
      "Casual Dining",
      "Sports Bar",

    ],
    giftIdeas: 9,
  },
  {
    id: 9,
    name: "Carnival Restaurant & Lounge",
    image:
      "https://images.pexels.com/photos/31321825/pexels-photo-31321825.jpeg",
    rating: 9,
    category: "Food",
    badges: [
      "Cocktails",
      "Shisha Lounge",
      "Nightlife",
      "Dance Floor",
      "DJ Sets",

    ],
    giftIdeas: 9,
  },
  {
    id: 10,
    name: "Wakame Restaurant",
    image:
      "https://images.pexels.com/photos/33150831/pexels-photo-33150831.jpeg",
    rating: 9,
    category: "Food",
    badges: [
      "Asian Fusion",
      "Sushi",
      "Noodles",
      "Teppanyaki",
      "Vegetarian",
  
    ],
    giftIdeas: 9,
  },
  {
    id: 11,
    name: "SEE Restaurant",
    image: "https://images.pexels.com/photos/70497/pexels-photo-70497.jpeg",
    rating: 9,
    category: "Food",
    badges: [
      "Seafood",
      "Steaks",
      "Mediterranean",
      "Romantic",
      "Luxury Dining",

    ],
    giftIdeas: 9,
  },
  {
    id: 12,
    name: "Sundays",
    image: "https://images.pexels.com/photos/1633525/pexels-photo-1633525.jpeg",
    rating: 9,
    category: "Food",
    badges: [
      "Breakfast",
      "Pancakes",
      "Smoothies",
      "Coffee",
      "Family Friendly",
      "Casual Dining",
      "Outdoor Seating",
    ],
    giftIdeas: 9,
  },

  // --- new vendors (13–20) ---
  {
    id: 13,
    name: "The Grill Room",
    image: "https://images.pexels.com/photos/189293/pexels-photo-189293.jpeg",
    rating: 8,
    category: "Food",
    badges: [
      "Steaks",
      "BBQ",
      "Craft Beer",
      "Casual Dining",
      "Sports Screenings",
      "Happy Hour",
    ],
    giftIdeas: 8,
  },
  {
    id: 14,
    name: "Lush Rooftop Bar",
    image: "https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg",
    rating: 9,
    category: "Food",
    badges: [
      "Cocktails",
      "Rooftop View",
      "Nightlife",
      "Live DJ",
      "Tapas",
      "VIP Area",
    ],
    giftIdeas: 9,
  },
  {
    id: 15,
    name: "Mama’s Kitchen",
    image: "https://images.pexels.com/photos/70497/pexels-photo-70497.jpeg",
    rating: 8,
    category: "Food",
    badges: [
      "African Cuisine",
      "Family Friendly",
      "Takeout",
      "Local Specialties",
      "Casual Dining",
    ],
    giftIdeas: 7,
  },
  {
    id: 16,
    name: "Green Bowl Café",
    image: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg",
    rating: 8,
    category: "Food",
    badges: [
      "Vegan",
      "Vegetarian",
      "Gluten-Free",
      "Smoothies",
      "Healthy Eating",
      "Organic",
    ],
    giftIdeas: 8,
  },
  {
    id: 17,
    name: "Spice Route",
    image: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg",
    rating: 9,
    category: "Food",
    badges: [
      "Indian Cuisine",
      "Curries",
      "Tandoor",
      "Vegetarian Options",
      "Family Style",
    ],
    giftIdeas: 9,
  },
  {
    id: 18,
    name: "La Patisserie",
    image: "https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg",
    rating: 9,
    category: "Food",
    badges: [
      "Bakery",
      "Pastries",
      "Coffee",
      "Desserts",
      "French Cuisine",
      "Brunch",
    ],
    giftIdeas: 9,
  },
  {
    id: 19,
    name: "Ocean Breeze",
    image: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg",
    rating: 10,
    category: "Food",
    badges: [
      "Seafood",
      "Beachfront",
      "Cocktails",
      "Romantic",
      "Luxury Dining",
      "Live Music",
    ],
    giftIdeas: 10,
  },
  {
    id: 20,
    name: "Burger Shack",
    image: "https://images.pexels.com/photos/1639567/pexels-photo-1639567.jpeg",
    rating: 8,
    category: "Food",
    badges: [
      "Burgers",
      "Fries",
      "Milkshakes",
      "Casual Dining",
      "Takeaway",
      "Late Night",
    ],
    giftIdeas: 7,
  },
];



// /data/vendors.ts

export const vendors_fashion: Vendor[] = [
  // --- vendors (1–20) ---
  {
    id: 1,
    name: "Zara",
    image: "https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg",
    rating: 9,
    category: "Fashion",
    badges: [
      "Trendy",
      "Casual Wear",
      "Workwear",
      "Accessories",
      "Fast Fashion",
    ],
    giftIdeas: 9,
  },
  {
    id: 2,
    name: "H&M",
    image: "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg",
    rating: 8,
    category: "Fashion",
    badges: [
      "Affordable",
      "Basics",
      "Kidswear",
      "Conscious Collection",
      "Seasonal Trends",
    ],
    giftIdeas: 8,
  },
  {
    id: 3,
    name: "Nike",
    image: "https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg",
    rating: 10,
    category: "Fashion",
    badges: [
      "Sportswear",
      "Sneakers",
      "Performance Gear",
      "Lifestyle",
      "Athleisure",
    ],
    giftIdeas: 10,
  },
  {
    id: 4,
    name: "Adidas",
    image: "https://images.pexels.com/photos/298864/pexels-photo-298864.jpeg",
    rating: 9,
    category: "Fashion",
    badges: [
      "Sportswear",
      "Originals",
      "Sneakers",
      "Tracksuits",
      "Athleisure",
    ],
    giftIdeas: 9,
  },
  {
    id: 5,
    name: "Gucci",
    image: "https://images.pexels.com/photos/298866/pexels-photo-298866.jpeg",
    rating: 10,
    category: "Fashion",
    badges: [
      "Luxury",
      "Designer",
      "Leather Goods",
      "Bags",
      "Shoes",
      "Accessories",
    ],
    giftIdeas: 10,
  },
  {
    id: 6,
    name: "Louis Vuitton",
    image: "https://images.pexels.com/photos/298867/pexels-photo-298867.jpeg",
    rating: 10,
    category: "Fashion",
    badges: [
      "Luxury",
      "Travel",
      "Designer",
      "Leather Goods",
      "Handbags",
      "Fashion Shows",
    ],
    giftIdeas: 10,
  },
  {
    id: 7,
    name: "Balenciaga",
    image: "https://images.pexels.com/photos/298868/pexels-photo-298868.jpeg",
    rating: 9,
    category: "Fashion",
    badges: [
      "High Fashion",
      "Sneakers",
      "Streetwear",
      "Bold Designs",
      "Luxury",
    ],
    giftIdeas: 9,
  },
  {
    id: 8,
    name: "Prada",
    image: "https://images.pexels.com/photos/298869/pexels-photo-298869.jpeg",
    rating: 9,
    category: "Fashion",
    badges: [
      "Italian Luxury",
      "Minimalist",
      "Handbags",
      "Shoes",
      "Accessories",
    ],
    giftIdeas: 9,
  },
  {
    id: 9,
    name: "Uniqlo",
    image: "https://images.pexels.com/photos/298870/pexels-photo-298870.jpeg",
    rating: 8,
    category: "Fashion",
    badges: [
      "Minimalist",
      "Everyday Basics",
      "Casual",
      "Functional",
      "Affordable",
    ],
    giftIdeas: 8,
  },
  {
    id: 10,
    name: "Levi’s",
    image: "https://images.pexels.com/photos/298871/pexels-photo-298871.jpeg",
    rating: 9,
    category: "Fashion",
    badges: [
      "Denim",
      "Jeans",
      "Casual Wear",
      "American Classic",
      "Streetwear",
    ],
    giftIdeas: 9,
  },
  {
    id: 11,
    name: "Chanel",
    image: "https://images.pexels.com/photos/298872/pexels-photo-298872.jpeg",
    rating: 10,
    category: "Fashion",
    badges: [
      "Luxury",
      "Couture",
      "Perfumes",
      "Handbags",
      "Classic",
      "Timeless",
    ],
    giftIdeas: 10,
  },
  {
    id: 12,
    name: "Dior",
    image: "https://images.pexels.com/photos/298873/pexels-photo-298873.jpeg",
    rating: 10,
    category: "Fashion",
    badges: [
      "Luxury",
      "Designer",
      "Perfume",
      "Handbags",
      "Haute Couture",
    ],
    giftIdeas: 10,
  },
  {
    id: 13,
    name: "Off-White",
    image: "https://images.pexels.com/photos/298874/pexels-photo-298874.jpeg",
    rating: 9,
    category: "Fashion",
    badges: [
      "Streetwear",
      "Sneakers",
      "Bold Designs",
      "Collabs",
      "Luxury Casual",
    ],
    giftIdeas: 9,
  },
  {
    id: 14,
    name: "Tommy Hilfiger",
    image: "https://images.pexels.com/photos/298875/pexels-photo-298875.jpeg",
    rating: 8,
    category: "Fashion",
    badges: [
      "Classic American",
      "Casual Wear",
      "Preppy",
      "Smart Casual",
      "Accessories",
    ],
    giftIdeas: 8,
  },
  {
    id: 15,
    name: "Calvin Klein",
    image: "https://images.pexels.com/photos/298876/pexels-photo-298876.jpeg",
    rating: 8,
    category: "Fashion",
    badges: [
      "Minimalist",
      "Underwear",
      "Jeans",
      "Casual Wear",
      "Fragrance",
    ],
    giftIdeas: 8,
  },
  {
    id: 16,
    name: "Fendi",
    image: "https://images.pexels.com/photos/298877/pexels-photo-298877.jpeg",
    rating: 9,
    category: "Fashion",
    badges: [
      "Luxury",
      "Bags",
      "Shoes",
      "Designer Wear",
      "Italian Style",
    ],
    giftIdeas: 9,
  },
  {
    id: 17,
    name: "Hermès",
    image: "https://images.pexels.com/photos/298878/pexels-photo-298878.jpeg",
    rating: 10,
    category: "Fashion",
    badges: [
      "Luxury",
      "Leather Goods",
      "Scarves",
      "Handbags",
      "Couture",
    ],
    giftIdeas: 10,
  },
  {
    id: 18,
    name: "Burberry",
    image: "https://images.pexels.com/photos/298879/pexels-photo-298879.jpeg",
    rating: 9,
    category: "Fashion",
    badges: [
      "British Luxury",
      "Trench Coats",
      "Plaid Pattern",
      "Accessories",
      "Classic",
    ],
    giftIdeas: 9,
  },
  {
    id: 19,
    name: "Ralph Lauren",
    image: "https://images.pexels.com/photos/298880/pexels-photo-298880.jpeg",
    rating: 9,
    category: "Fashion",
    badges: [
      "Polo",
      "Classic American",
      "Luxury Casual",
      "Smart Wear",
      "Accessories",
    ],
    giftIdeas: 9,
  },
  {
    id: 20,
    name: "Versace",
    image: "https://images.pexels.com/photos/298881/pexels-photo-298881.jpeg",
    rating: 10,
    category: "Fashion",
    badges: [
      "Italian Luxury",
      "Bold Prints",
      "Runway",
      "Designer Wear",
      "Perfumes",
    ],
    giftIdeas: 10,
  },
];


export const vendors_gadget: Vendor[] = [
  // --- existing vendors (1–12) ---
  {
    id: 1,
    name: "TechNova Gadgets",
    image: "https://images.pexels.com/photos/7974/pexels-photo.jpg",
    rating: 9,
    category: "Gadget",
    badges: [
      "Smartphones",
      "Laptops",
      "Accessories",
      "Warranties",
      "Tech Support",
    ],
    giftIdeas: 9,
  },
  {
    id: 2,
    name: "Gizmo World",
    image: "https://images.pexels.com/photos/1714208/pexels-photo-1714208.jpeg",
    rating: 9,
    category: "Gadget",
    badges: [
      "Drones",
      "Cameras",
      "Wearables",
      "Gaming Consoles",
      "VR Headsets",
    ],
    giftIdeas: 9,
  },
  {
    id: 3,
    name: "ElectroHub",
    image: "https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg",
    rating: 9,
    category: "Gadget",
    badges: ["Tablets", "Earbuds", "Chargers", "Smart Home", "Audio Systems"],
    giftIdeas: 9,
  },
  {
    id: 4,
    name: "InnoTech Store",
    image: "https://images.pexels.com/photos/373076/pexels-photo-373076.jpeg",
    rating: 9,
    category: "Gadget",
    badges: ["Laptops", "Desktops", "Monitors", "Keyboards", "Mice"],
    giftIdeas: 9,
  },
  {
    id: 5,
    name: "Gadget Galaxy",
    image: "https://images.pexels.com/photos/777001/pexels-photo-777001.jpeg",
    rating: 9,
    category: "Gadget",
    badges: [
      "Smartwatches",
      "Fitness Trackers",
      "Bluetooth Speakers",
      "Power Banks",
      "Cables",
    ],
    giftIdeas: 9,
  },
  {
    id: 6,
    name: "Future Tech",
    image: "https://images.pexels.com/photos/325153/pexels-photo-325153.jpeg",
    rating: 9,
    category: "Gadget",
    badges: [
      "AR Glasses",
      "Robotics",
      "IoT Devices",
      "Security Cams",
      "Smart Lights",
    ],
    giftIdeas: 9,
  },
  {
    id: 7,
    name: "Byte Boutique",
    image: "https://images.pexels.com/photos/204611/pexels-photo-204611.jpeg",
    rating: 9,
    category: "Gadget",
    badges: ["Gaming PCs", "Controllers", "Headsets", "Monitors", "Chairs"],
    giftIdeas: 9,
  },
  {
    id: 8,
    name: "Spark Electronics",
    image:
      "https://images.pexels.com/photos/163117/keyboard-apple-computer-laptop-163117.jpeg",
    rating: 9,
    category: "Gadget",
    badges: ["Phones", "Cases", "Screen Protectors", "Chargers", "Adapters"],
    giftIdeas: 9,
  },
  {
    id: 9,
    name: "Nova Devices",
    image: "https://images.pexels.com/photos/248528/pexels-photo-248528.jpeg",
    rating: 9,
    category: "Gadget",
    badges: ["Tablets", "E-Readers", "Styluses", "Covers", "Stands"],
    giftIdeas: 9,
  },
  {
    id: 10,
    name: "Circuit City",
    image: "https://images.pexels.com/photos/459653/pexels-photo-459653.jpeg",
    rating: 9,
    category: "Gadget",
    badges: [
      "Home Appliances",
      "Smart TVs",
      "Soundbars",
      "Projectors",
      "Remotes",
    ],
    giftIdeas: 9,
  },
  {
    id: 11,
    name: "Pulse Gadgets",
    image: "https://images.pexels.com/photos/2300334/pexels-photo-2300334.jpeg",
    rating: 9,
    category: "Gadget",
    badges: [
      "Fitness Gadgets",
      "Heart Monitors",
      "Scales",
      "Activity Trackers",
      "Apps Integration",
    ],
    giftIdeas: 9,
  },
  {
    id: 12,
    name: "Zen Tech",
    image: "https://images.pexels.com/photos/1714205/pexels-photo-1714205.jpeg",
    rating: 9,
    category: "Gadget",
    badges: [
      "Meditation Devices",
      "Noise Cancelling",
      "Sleep Trackers",
      "Aromatherapy Diffusers",
      "Wellness Apps",
    ],
    giftIdeas: 9,
  },

  // --- new vendors (13–20) ---
  {
    id: 13,
    name: "Gear Up Store",
    image: "https://images.pexels.com/photos/1647976/pexels-photo-1647976.jpeg",
    rating: 8,
    category: "Gadget",
    badges: [
      "Outdoor Gadgets",
      "GPS Devices",
      "Action Cams",
      "Portable Chargers",
      "Backpacks",
    ],
    giftIdeas: 8,
  },
  {
    id: 14,
    name: "Vibe Electronics",
    image: "https://images.pexels.com/photos/1647972/pexels-photo-1647972.jpeg",
    rating: 9,
    category: "Gadget",
    badges: [
      "Party Speakers",
      "LED Lights",
      "Microphones",
      "DJ Equipment",
      "Wireless Systems",
    ],
    giftIdeas: 9,
  },
  {
    id: 15,
    name: "Eco Tech",
    image: "https://images.pexels.com/photos/1714340/pexels-photo-1714340.jpeg",
    rating: 8,
    category: "Gadget",
    badges: [
      "Solar Chargers",
      "Eco-Friendly Cases",
      "Reusable Batteries",
      "Energy Monitors",
      "Green Tech",
    ],
    giftIdeas: 7,
  },
  {
    id: 16,
    name: "Smart Haven",
    image: "https://images.pexels.com/photos/373076/pexels-photo-373076.jpeg",
    rating: 8,
    category: "Gadget",
    badges: [
      "Home Automation",
      "Voice Assistants",
      "Smart Locks",
      "Thermostats",
      "Cameras",
    ],
    giftIdeas: 8,
  },
  {
    id: 17,
    name: "Pixel Palace",
    image: "https://images.pexels.com/photos/777001/pexels-photo-777001.jpeg",
    rating: 9,
    category: "Gadget",
    badges: ["Cameras", "Lenses", "Tripods", "Drones", "Editing Software"],
    giftIdeas: 9,
  },
  {
    id: 18,
    name: "Code Crafters",
    image: "https://images.pexels.com/photos/325153/pexels-photo-325153.jpeg",
    rating: 9,
    category: "Gadget",
    badges: [
      "Coding Kits",
      "Raspberry Pi",
      "Arduino",
      "Sensors",
      "DIY Electronics",
    ],
    giftIdeas: 9,
  },
  {
    id: 19,
    name: "Elite Gadgets",
    image: "https://images.pexels.com/photos/204611/pexels-photo-204611.jpeg",
    rating: 10,
    category: "Gadget",
    badges: [
      "Premium Phones",
      "High-End Laptops",
      "Luxury Watches",
      "Gold-Plated Accessories",
      "VIP Service",
    ],
    giftIdeas: 10,
  },
  {
    id: 20,
    name: "Quick Fix Tech",
    image:
      "https://images.pexels.com/photos/163117/keyboard-apple-computer-laptop-163117.jpeg",
    rating: 8,
    category: "Gadget",
    badges: [
      "Repair Services",
      "Replacement Parts",
      "Tools",
      "Diagnostics",
      "Upgrades",
    ],
    giftIdeas: 7,
  },
];


// /data/vendors.ts

export const vendors_lifestyle: Vendor[] = [
  {
    id: 1,
    name: "Zen Spa & Wellness",
    image: "https://images.pexels.com/photos/6620932/pexels-photo-6620932.jpeg",
    rating: 9,
    category: "Lifestyle",
    badges: [
      "Spa",
      "Massage",
      "Sauna",
      "Relaxation",
      "Luxury",
    ],
    giftIdeas: 9,
  },
  {
    id: 2,
    name: "Pulse Fitness",
    image: "https://images.pexels.com/photos/1954524/pexels-photo-1954524.jpeg",
    rating: 8,
    category: "Lifestyle",
    badges: [
      "Gym",
      "Personal Training",
      "CrossFit",
      "Wellness",
      "Cardio",
    ],
    giftIdeas: 8,
  },
  {
    id: 3,
    name: "Glow Beauty Bar",
    image: "https://images.pexels.com/photos/853427/pexels-photo-853427.jpeg",
    rating: 9,
    category: "Lifestyle",
    badges: [
      "Makeup",
      "Skincare",
      "Facials",
      "Nails",
      "Beauty Products",
    ],
    giftIdeas: 9,
  },
  {
    id: 4,
    name: "Yoga Flow Studio",
    image: "https://images.pexels.com/photos/3759657/pexels-photo-3759657.jpeg",
    rating: 8,
    category: "Lifestyle",
    badges: [
      "Yoga",
      "Meditation",
      "Pilates",
      "Mindfulness",
      "Workshops",
    ],
    giftIdeas: 8,
  },
  {
    id: 5,
    name: "Escape Travel",
    image: "https://images.pexels.com/photos/346885/pexels-photo-346885.jpeg",
    rating: 9,
    category: "Lifestyle",
    badges: [
      "Tours",
      "Vacation",
      "Adventure",
      "Luxury Travel",
      "Getaways",
    ],
    giftIdeas: 9,
  },
  {
    id: 6,
    name: "Cycle Hub",
    image: "https://images.pexels.com/photos/1552249/pexels-photo-1552249.jpeg",
    rating: 8,
    category: "Lifestyle",
    badges: [
      "Cycling",
      "Spin Classes",
      "Cardio",
      "Endurance",
      "Group Training",
    ],
    giftIdeas: 8,
  },
  {
    id: 7,
    name: "Aqua Wellness",
    image: "https://images.pexels.com/photos/267566/pexels-photo-267566.jpeg",
    rating: 9,
    category: "Lifestyle",
    badges: [
      "Swimming",
      "Hydrotherapy",
      "Relaxation",
      "Wellness",
      "Sports Training",
    ],
    giftIdeas: 9,
  },
  {
    id: 8,
    name: "Serenity Retreat",
    image: "https://images.pexels.com/photos/3759658/pexels-photo-3759658.jpeg",
    rating: 10,
    category: "Lifestyle",
    badges: [
      "Retreat",
      "Meditation",
      "Yoga",
      "Spa",
      "Nature Escape",
    ],
    giftIdeas: 10,
  },
  {
    id: 9,
    name: "Luxury Nails Studio",
    image: "https://images.pexels.com/photos/853427/pexels-photo-853427.jpeg",
    rating: 8,
    category: "Lifestyle",
    badges: [
      "Nail Art",
      "Manicure",
      "Pedicure",
      "Luxury",
      "Beauty Care",
    ],
    giftIdeas: 8,
  },
  {
    id: 10,
    name: "Wellness Market",
    image: "https://images.pexels.com/photos/1300972/pexels-photo-1300972.jpeg",
    rating: 9,
    category: "Lifestyle",
    badges: [
      "Organic",
      "Healthy Living",
      "Supplements",
      "Skincare",
      "Wellness Products",
    ],
    giftIdeas: 9,
  },
  {
    id: 11,
    name: "Urban Escape Spa",
    image: "https://images.pexels.com/photos/6620932/pexels-photo-6620932.jpeg",
    rating: 9,
    category: "Lifestyle",
    badges: [
      "Massage",
      "Aromatherapy",
      "Skin Treatments",
      "Relaxation",
      "Luxury",
    ],
    giftIdeas: 9,
  },
  {
    id: 12,
    name: "Elite Gym Club",
    image: "https://images.pexels.com/photos/1954524/pexels-photo-1954524.jpeg",
    rating: 8,
    category: "Lifestyle",
    badges: [
      "Fitness",
      "Weightlifting",
      "CrossFit",
      "HIIT",
      "Personal Coaching",
    ],
    giftIdeas: 8,
  },
  {
    id: 13,
    name: "Skyline Travel",
    image: "https://images.pexels.com/photos/346885/pexels-photo-346885.jpeg",
    rating: 9,
    category: "Lifestyle",
    badges: [
      "Luxury Travel",
      "Adventure",
      "City Breaks",
      "Honeymoon",
      "Family Trips",
    ],
    giftIdeas: 9,
  },
  {
    id: 14,
    name: "Bliss Yoga House",
    image: "https://images.pexels.com/photos/3759657/pexels-photo-3759657.jpeg",
    rating: 8,
    category: "Lifestyle",
    badges: [
      "Yoga",
      "Sound Healing",
      "Meditation",
      "Retreats",
      "Holistic Wellness",
    ],
    giftIdeas: 8,
  },
  {
    id: 15,
    name: "Glow Skincare Lounge",
    image: "https://images.pexels.com/photos/853427/pexels-photo-853427.jpeg",
    rating: 9,
    category: "Lifestyle",
    badges: [
      "Facials",
      "Dermatology",
      "Skin Treatments",
      "Luxury Products",
      "Beauty",
    ],
    giftIdeas: 9,
  },
  {
    id: 16,
    name: "Adventure Hub",
    image: "https://images.pexels.com/photos/238622/pexels-photo-238622.jpeg",
    rating: 9,
    category: "Lifestyle",
    badges: [
      "Hiking",
      "Kayaking",
      "Climbing",
      "Adventure Tours",
      "Outdoor Activities",
    ],
    giftIdeas: 9,
  },
  {
    id: 17,
    name: "Tranquil Spa",
    image: "https://images.pexels.com/photos/6620932/pexels-photo-6620932.jpeg",
    rating: 10,
    category: "Lifestyle",
    badges: [
      "Spa",
      "Luxury",
      "Massage",
      "Sauna",
      "Wellness",
    ],
    giftIdeas: 10,
  },
  {
    id: 18,
    name: "Glow Hair Studio",
    image: "https://images.pexels.com/photos/853427/pexels-photo-853427.jpeg",
    rating: 8,
    category: "Lifestyle",
    badges: [
      "Haircut",
      "Styling",
      "Coloring",
      "Luxury Salon",
      "Bridal",
    ],
    giftIdeas: 8,
  },
  {
    id: 19,
    name: "Harmony Wellness Center",
    image: "https://images.pexels.com/photos/267566/pexels-photo-267566.jpeg",
    rating: 9,
    category: "Lifestyle",
    badges: [
      "Holistic",
      "Massage",
      "Yoga",
      "Meditation",
      "Wellness Retreat",
    ],
    giftIdeas: 9,
  },
  {
    id: 20,
    name: "Global Getaways",
    image: "https://images.pexels.com/photos/346885/pexels-photo-346885.jpeg",
    rating: 10,
    category: "Lifestyle",
    badges: [
      "Luxury Travel",
      "Adventure",
      "Cultural Tours",
      "Beach Resorts",
      "Romantic Escapes",
    ],
    giftIdeas: 10,
  },
];
